/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Pessoa;
import interfaces.InterfaceForm;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Base64;
import java.util.Date;
import javax.swing.JOptionPane;
import lib.ComboItens;
import lib.GenericCombo;
import model.PessoaModel;
import lib.GenericForm;

/**
 *
 * @author Cristiano Peiter <cristiano.peiter@universo.univates.br>
 */
public final class LoginForm extends GenericForm<Pessoa> implements InterfaceForm {

    public PessoaModel model;
    public Pessoa obj;
    public ArrayList<String> camposObrigatorios;

    public LoginForm(java.awt.Frame parent, boolean modal) {
        //novo
        super(Pessoa.class, parent, modal);
        this.construtorPadrao();
    }

    public LoginForm(java.awt.Frame parent, boolean modal, int id) throws Exception {
        //edição
        super(Pessoa.class, parent, modal);
        this.construtorPadrao();
        this.preencherCampos(id);
    }

    private void construtorPadrao() {
        //iniciando componentes
        initComponents();

        //atributos da tela                
        super.setTitle("Cadastro de Pessoas");
        this.model = new PessoaModel();
        this.camposObrigatorios = new ArrayList<>();
        this.obj = new Pessoa();

        //campos obrigatorios        
        this.camposObrigatorios.add("nome");
        this.nome.setName("nome");

        this.camposObrigatorios.add("cpf");
        this.cpf.setName("cpf");

        this.camposObrigatorios.add("login");
        this.login.setName("login");

        this.camposObrigatorios.add("senha");
        this.senha.setName("senha");
        
        this.camposObrigatorios.add("ativo");
        this.ativo.setName("ativo");

        this.camposObrigatorios.add("ref_cidade");
        this.ref_cidade.setName("ref_cidade");

        this.camposObrigatorios.add("ref_nivel_acesso");
        this.ref_nivel_acesso.setName("ref_nivel_acesso");

        // popula combos
        this.ref_cidade.removeAllItems();
        this.ref_nivel_acesso.removeAllItems();
        this.genero.removeAllItems();
        try 
        {
            new GenericCombo().popularCombo("cidade", this.ref_cidade);
            new GenericCombo().popularCombo("nivel_acesso", this.ref_nivel_acesso);
            
            genero.addItem("F");
            genero.addItem("M");
        } 
        catch (Exception ex) 
        {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao popular combo. \nErro: " + ex, "Error", JOptionPane.ERROR_MESSAGE);
        }

        //desabilitar campo codigo
        this.id.disable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        login = new javax.swing.JTextField();
        endereco = new javax.swing.JTextField();
        genero = new javax.swing.JComboBox<>();
        salvarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("<html>Funcionário:<font color = red>*</font></html>");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Código:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("<html>Senha:<font color = red>*</font></html>");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("<html>Usuário:<font color = red>*</font></html>");

        id.setEditable(false);

        genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        salvarButton.setText("Salvar");
        salvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(salvarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(login))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endereco))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        sair();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void salvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButtonActionPerformed
        try {
            if (salvar())
            {
                JOptionPane.showMessageDialog(null, "Registro gravado com sucesso.", "Info", JOptionPane.INFORMATION_MESSAGE);
                sair();
            }
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao gravar o registro. \nErro: " + ex, "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
            return;
        }
    }//GEN-LAST:event_salvarButtonActionPerformed

    @Override
    public boolean salvar() throws Exception 
    {
        boolean fl_gravou;

        if (validarCampos(this.camposObrigatorios, this.jPanel1)) 
        {
            if (!"".equals(this.id.getText())) 
            {
                this.obj.setId(Integer.parseInt(this.id.getText()));
            }
            
            String encodedSenha = Base64.getEncoder().withoutPadding().encodeToString(this.senha.getText().getBytes());
            
            //seta data de nascimento
            if (!"".equals(this.nascimento.getText())) 
            {
                try
                {
                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

                    Date dtNascimento = sdf.parse(this.nascimento.getText());
                    this.obj.setNascimento(dtNascimento);
                }
                catch(Exception ex)
                {
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro ao cadastrar a data de nascimento. \nErro: " + ex, "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            
            Timestamp dataDeHoje = new Timestamp(System.currentTimeMillis());
            
            this.obj.setDt_cadastro(dataDeHoje);
            
            this.obj.setNome(this.nome.getText());
            this.obj.setCpf(this.cpf.getText());
            this.obj.setLogin(this.login.getText());
            this.obj.setSenha(encodedSenha);
            this.obj.setEndereco(this.endereco.getText());
            this.obj.setTelefone(this.telefone.getText());
            this.obj.setEmail(this.email.getText());
            this.obj.setGenero(this.genero.getSelectedItem().toString());
            this.obj.setAtivo(this.ativo.isSelected() ? 1 : 0);

            //combo cidade            
            ComboItens cb_cidade = (ComboItens) this.ref_cidade.getSelectedItem();
            this.obj.setRef_cidade(cb_cidade.getCodigo());

            //combo nivel
            ComboItens cb_nivel_acesso = (ComboItens) this.ref_nivel_acesso.getSelectedItem();
            this.obj.setRef_nivel_acesso(cb_nivel_acesso.getCodigo());

            this.model.store(this.obj);
            fl_gravou = true;
        } 
        else 
        {
            JOptionPane.showMessageDialog(null, "Preencha os campos obrigatórios corretamente.", "Info", JOptionPane.INFORMATION_MESSAGE);
            fl_gravou = false;
        }

        return fl_gravou;
    }

    @Override
    public void preencherCampos(int id) throws Exception 
    {
        //carrega obj
        this.obj = this.model.getObject(id);
        System.out.println(this.obj.getNascimento());
        if( this.obj.getNascimento() != null )
        {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            String strNascimento = sdf.format(this.obj.getNascimento());
            this.nascimento.setText(String.valueOf(strNascimento));
        }
        
        byte [] decodedSenha = Base64.getDecoder().decode(this.obj.getSenha());
        String trueSenha = new String(decodedSenha);

        //preenche obj
        this.id.setText(String.valueOf(this.obj.getId()));
        this.nome.setText(this.obj.getNome());
        this.cpf.setText(this.obj.getCpf());
        this.login.setText(this.obj.getLogin());
        this.senha.setText(trueSenha);
        if( this.obj.getEndereco() != null )
        {
            this.endereco.setText(this.obj.getEndereco());
        }
        if( this.obj.getTelefone() != null )
        {
            this.telefone.setText(this.obj.getTelefone());
        }
        if( this.obj.getEmail() != null )
        {
            this.email.setText(this.obj.getEmail());
        }
        this.genero.setSelectedItem(this.obj.getGenero());
        this.telefone.setText(this.obj.getTelefone());
        this.ativo.setSelected(this.obj.getAtivo() == 1);
        

        //combos
        new GenericCombo().definirItemCombo(this.ref_cidade, this.obj.getRef_cidade());
        new GenericCombo().definirItemCombo(this.ref_nivel_acesso, this.obj.getRef_nivel_acesso());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                LoginForm dialog = new LoginForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() 
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) 
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarButton;
    private javax.swing.JTextField endereco;
    private javax.swing.JComboBox<String> genero;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField login;
    private javax.swing.JButton salvarButton;
    // End of variables declaration//GEN-END:variables
}
